server:
  port: 8090
spring:
  profiles:
    active:
     - "qa"
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
build:
  version: "2.0"
loans:
  message: "Welcome to ZettaBank loans related APIs"
  contactDetails:
    name: "Mounika Uppuluru - Developer"
    email: "umounika@zettabank.com"
  onCallSupport:
    - (40) 123-45678
    - (40) 456-13459
